roadblockFolder='../data/Landscape/PeterDriving/';
rawblockname={'Flat' 'Right180B' 'StartUp' 'Left180' ...
    'Right30' 'loop1' 'Left180B' 'Right45' ...
    'loop2' 'EndDown' 'Left45' 'Right45B' ...
    'EndDown' 'Left45B' 'ShortFlat' 'EndUp' 'Right180' 'StartDown'};
rawblockname={'Flat' 'Right180B' 'StartUp' 'Left180' ...
    'Right30' 'loop1' 'Left180B' 'Right45' ...
    'loop2' 'EndDown' 'Left45' 'Right45B' ...
    'EndDown' 'Left45B' 'ShortFlat' 'EndUp' 'Right180' 'StartDown'};
nBlock=length(rawblockname);